### PR TITLE
Add support for Java 12, 13 and 14

### PR DESCRIPTION
**Pull request by njbartlett**

### CODE REVIEW

**Comment by rotty3000** [comment]
Couldn't the Java version be an argument to the template? Derived or requested at time of executing the achetype? I find the duplication to be superfluous and after another 4 years you're gonna have 8 more copies? Also why bother with the non-LTS versions (except perhaps the latest one.)

**Comment by njbartlett** [comment]
It already is an argument to the template. The user controls the Java version this when they generate a new project by setting e.g. `-Dapp-target-java-version=12`. The duplication is in the test data, i.e. the reference projects used to check the output of the archetype. I didn't invent this system, I have only extended it to new versions.

I would tend to agree regarding LTS only, but that creates two new issues.

First, what if the user requests Java 10? Do we give them 11, or 1.8? From the template language (Velocity) there is no real way to throw an exception based on bad input... we have to produce *something*.

Second problem is that Java 13 is already EOL, but it looks like we can't yet build with Java 14 on AppVeyor. I used the matrix [here](https://www.appveyor.com/docs/windows-images-software/#java) but it doesn't look like the node didn't actually have JDK 14 installed. Could somebody with access to the AppVeyor account look into this?

**Comment by rotty3000** [comment]
Like we have done elsewhere, I wonder if we should change CI to github actions. The matrix is very extensive including EA releases. Also it supports mac and windows builds of same. Finally, it's super easy to configure and it's all done in the repository. I could take a shot at configuring it in the next while. First try will likely be a copy&paste from the bnd project :)

**Comment by bjhargrave** [comment]
I updated the build to github actions. So this PR will need to be reworked.

**Comment by bjhargrave** [comment]
Once fixed, this will need to be resubmitted against the `main` branch.

**Pull request closed without merging**
